[package]
name = "telemetry_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
egui_plot = "0.27"
serialport = "4.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "4.5.53"
